# Generated by Django 4.2.4 on 2023-08-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Освітній заклад',
                'verbose_name_plural': 'Освітній заклад',
                'db_table': 'cl_educational_institutions',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мови',
                'db_table': 'cl_languages',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Регіон роботи',
                'verbose_name_plural': 'Регіони роботи',
                'db_table': 'cl_regions',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Спеціалізація',
                'verbose_name_plural': 'Спеціалізації',
                'db_table': 'cl_speciality',
            },
        ),
        migrations.CreateModel(
            name='WorkFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Формат роботи',
                'verbose_name_plural': 'Формати роботи',
                'db_table': 'cl_work_formats',
            },
        ),
        migrations.CreateModel(
            name='EducationalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('educational_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifiers.educationalinstitution')),
            ],
            options={
                'verbose_name': 'Навчальний курс',
                'verbose_name_plural': 'Навчальні курси',
                'db_table': 'cl_educational_courses',
            },
        ),
    ]
