# Generated by Django 4.2.4 on 2023-08-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Спеціалізація',
                'verbose_name_plural': 'Спеціалізації',
                'db_table': 'cl_specializations',
            },
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Спеціальність', 'verbose_name_plural': 'Спеціальності'},
        ),
        migrations.AlterModelTable(
            name='speciality',
            table='cl_specialities',
        ),
    ]
