# Generated by Django 4.2.4 on 2023-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0002_specialization_alter_speciality_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Професійний напрямок',
                'verbose_name_plural': 'Професійні напрямки',
                'db_table': 'cl_professional_directions',
            },
        ),
    ]
