# Generated by Django 4.2.4 on 2023-08-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0004_remove_educationalcourse_educational_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalcourse',
            options={'ordering': ('title',), 'verbose_name': 'Навчальний курс', 'verbose_name_plural': 'Навчальні курси'},
        ),
        migrations.AlterModelOptions(
            name='educationalinstitution',
            options={'ordering': ('title',), 'verbose_name': 'Освітній заклад', 'verbose_name_plural': 'Освітній заклад'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('title',), 'verbose_name': 'Мова', 'verbose_name_plural': 'Мови'},
        ),
    ]
