# Generated by Django 4.2.4 on 2023-08-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0005_alter_educationalcourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcourse',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
        migrations.AddField(
            model_name='language',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
        migrations.AddField(
            model_name='professionaldirections',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
        migrations.AddField(
            model_name='region',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
        migrations.AddField(
            model_name='workformat',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
    ]
