# Generated by Django 4.2.4 on 2023-08-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0006_educationalcourse_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('weight', 'created_at'), 'verbose_name': 'Мова', 'verbose_name_plural': 'Мови'},
        ),
        migrations.AlterModelOptions(
            name='professionaldirections',
            options={'ordering': ('weight', 'created_at'), 'verbose_name': 'Професійний напрямок', 'verbose_name_plural': 'Професійні напрямки'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('weight', 'created_at'), 'verbose_name': 'Регіон роботи', 'verbose_name_plural': 'Регіони роботи'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ('weight', 'created_at'), 'verbose_name': 'Спеціальність', 'verbose_name_plural': 'Спеціальності'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ('weight', 'created_at'), 'verbose_name': 'Спеціалізація', 'verbose_name_plural': 'Спеціалізації'},
        ),
        migrations.AlterModelOptions(
            name='workformat',
            options={'ordering': ('weight', 'created_at'), 'verbose_name': 'Формат роботи', 'verbose_name_plural': 'Формати роботи'},
        ),
        migrations.RemoveField(
            model_name='educationalcourse',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='educationalinstitution',
            name='weight',
        ),
    ]
