# Generated by Django 4.2.4 on 2023-08-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0007_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
    ]
