# Generated by Django 4.2.4 on 2023-10-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0008_alter_region_weight_alter_speciality_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionaldirections',
            options={'ordering': ('weight', 'created_at'), 'verbose_name': 'Спеціалізація медіатора у сфері інтелектуальної власності, сферах бізнесу', 'verbose_name_plural': 'Спеціалізації медіаторів у сфері інтелектуальної власності, сферах бізнесу'},
        ),
    ]
