# Generated by Django 4.2.4 on 2024-04-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0009_alter_professionaldirections_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcourse',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='educationalcourse',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='language',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Значення'),
        ),
        migrations.AddField(
            model_name='language',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Значення'),
        ),
        migrations.AddField(
            model_name='professionaldirections',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='professionaldirections',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='region',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='region',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='workformat',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Значення'),
        ),
        migrations.AddField(
            model_name='workformat',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Значення'),
        ),
    ]
