# Generated by Django 4.2.4 on 2024-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_hours_en',
            field=models.TextField(blank=True, null=True, verbose_name='Режим роботи'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_hours_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Режим роботи'),
        ),
    ]
