# Generated by Django 4.2.4 on 2023-08-09 21:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('application_number', models.CharField(max_length=255, verbose_name='Номер заяви')),
                ('application_date', models.DateField(verbose_name='Дата заяви')),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='По-батькові')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mediators/%Y/%m/%d', verbose_name='Фото')),
                ('professional_directions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Професійні напрямки')),
                ('address', models.TextField(blank=True, max_length=512, null=True, verbose_name='Адреса для листування')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна адреса')),
                ('phones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номери телефонів')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце роботи')),
                ('job_experience', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Досвід роботи')),
                ('mediators_membership', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Членство, займані посади в об’єднаннях медіаторів')),
                ('awards', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Нагороди, почесні звання')),
                ('price', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Вартість послуг медіації')),
                ('other', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Інше')),
                ('active', models.BooleanField(default=False, help_text='Визначає чи буде особу опубліковано на сайті', verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Медіатор',
                'verbose_name_plural': 'Медіатори',
                'db_table': 'mediators',
            },
        ),
        migrations.CreateModel(
            name='MediatorTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('training_type', models.CharField(choices=[('BASIC', 'Базова підготовка'), ('SPEC', 'Спеціалізована підготовка'), ('ADDITIONAL', 'Підвищення професійного рівня')], max_length=10, verbose_name='Тип підготовки')),
                ('hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість годин')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік')),
                ('certificate', models.FileField(help_text='Дозволені розширення файлу: pdf, jpg, jpeg, png, gif', upload_to='certificates/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'jpeg', 'png', 'gif'))], verbose_name='Файл сертифікату')),
                ('education_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifiers.educationalcourse', verbose_name='Назва курсу')),
                ('education_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifiers.educationalinstitution', verbose_name='Освітній заклад')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.mediator')),
            ],
            options={
                'verbose_name': 'Підготовка медіатора',
                'verbose_name_plural': 'Підготовка медіатора',
                'db_table': 'mediators_trainings',
            },
        ),
        migrations.CreateModel(
            name='MediatorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('year_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік з')),
                ('year_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік по')),
                ('certificate', models.FileField(help_text='Дозволені розширення файлу: pdf, jpg, jpeg, png, gif', upload_to='certificates/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'jpeg', 'png', 'gif'))], verbose_name='Файл сертифікату')),
                ('education_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifiers.educationalinstitution', verbose_name='Освітній заклад')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.mediator')),
            ],
            options={
                'verbose_name': 'Освіта',
                'verbose_name_plural': 'Освіта',
                'db_table': 'mediators_educations',
            },
        ),
        migrations.AddField(
            model_name='mediator',
            name='educations',
            field=models.ManyToManyField(blank=True, through='registry.MediatorEducation', to='classifiers.educationalinstitution'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='languages',
            field=models.ManyToManyField(blank=True, to='classifiers.language', verbose_name='Мова'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='regions',
            field=models.ManyToManyField(blank=True, to='classifiers.region', verbose_name='Регіон роботи'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='classifiers.speciality', verbose_name='Спеціальність'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='trainings',
            field=models.ManyToManyField(blank=True, related_name='basic_training', through='registry.MediatorTraining', to='classifiers.educationalcourse'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='work_formats',
            field=models.ManyToManyField(blank=True, to='classifiers.workformat', verbose_name='Формат роботи'),
        ),
    ]
