# Generated by Django 4.2.4 on 2023-08-14 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_mediator_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatoreducation',
            name='certificate',
            field=models.FileField(blank=True, help_text='Дозволені розширення файлу: pdf, jpg, jpeg, png, gif', null=True, upload_to='certificates/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'jpeg', 'png', 'gif'))], verbose_name='Файл сертифікату'),
        ),
        migrations.AlterField(
            model_name='mediatortraining',
            name='certificate',
            field=models.FileField(blank=True, help_text='Дозволені розширення файлу: pdf, jpg, jpeg, png, gif', null=True, upload_to='certificates/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'jpeg', 'png', 'gif'))], verbose_name='Файл сертифікату'),
        ),
    ]
