# Generated by Django 4.2.4 on 2023-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0003_professionaldirections'),
        ('registry', '0003_alter_mediatoreducation_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediator',
            name='professional_directions',
        ),
        migrations.AddField(
            model_name='mediator',
            name='professional_directions',
            field=models.ManyToManyField(blank=True, to='classifiers.professionaldirections', verbose_name='Професійні напрямки'),
        ),
    ]
