# Generated by Django 4.2.4 on 2023-08-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_remove_mediator_work_formats_mediator_work_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediator',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Оновлено'),
        ),
    ]
