# Generated by Django 4.2.4 on 2023-08-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_mediator_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediator',
            name='photo',
            field=models.ImageField(blank=True, help_text='Розмір зображення - 600*900 пікселей. Якщо зображення має інший розмір, то воно буде приведено до розміру 600*900 автоматично.', null=True, upload_to='mediators/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
