# Generated by Django 4.2.4 on 2023-08-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_mediator_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediator',
            name='last_change_reason',
            field=models.CharField(blank=True, choices=[('', '----'), ('tech', 'Технічні виправлення'), ('biblio', 'Зміни в бібліографії')], max_length=6, null=True, verbose_name='Причина змін'),
        ),
    ]
