# Generated by Django 4.2.4 on 2023-09-08 15:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_mediator_last_change_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('show', models.BooleanField(verbose_name='Відображати текст для користувачів веб-сайту')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Сторінка списку медіаторів',
                'verbose_name_plural': 'Сторінка списку медіаторів',
                'db_table': 'mediators_page',
            },
        ),
    ]
