# Generated by Django 4.2.4 on 2023-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0009_alter_professionaldirections_options'),
        ('registry', '0010_remove_mediator_awards_remove_mediator_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediator',
            name='professional_directions',
            field=models.ManyToManyField(blank=True, to='classifiers.professionaldirections', verbose_name='Спеціалізація медіатора у сфері інтелектуальної власності, сферах бізнесу'),
        ),
    ]
