# Generated by Django 4.2.4 on 2024-04-05 12:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_alter_mediator_professional_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediator',
            name='additional_info',
            field=ckeditor.fields.RichTextField(blank=True, max_length=16384, null=True, verbose_name='Додаткова інформація'),
        ),
    ]
