# Generated by Django 4.2.4 on 2024-04-05 13:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_alter_mediator_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
    ]
