# Generated by Django 4.2.4 on 2024-04-08 14:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_page_content_en_page_content_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediator',
            name='additional_info_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=16384, null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='additional_info_uk',
            field=ckeditor.fields.RichTextField(blank=True, max_length=16384, null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='first_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='mediator',
            name='first_name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='mediator',
            name='last_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='last_name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='middle_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По-батькові'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='middle_name_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По-батькові'),
        ),
    ]
