# Generated by Django 4.2.4 on 2024-04-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0011_alter_educationalinstitution_options'),
        ('registry', '0015_remove_mediator_professional_directions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediator',
            name='professional_directions',
            field=models.ManyToManyField(blank=True, through='registry.MediatorProfessionalDirections', to='classifiers.professionaldirections', verbose_name='Спеціалізація медіатора у сфері інтелектуальної власності, сферах бізнесу'),
        ),
    ]
