# Generated by Django 4.2.4 on 2024-04-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0012_alter_professionaldirections_title_and_more'),
        ('registry', '0016_mediator_professional_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatorprofessionaldirections',
            name='professional_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifiers.professionaldirections', verbose_name='Професійний напрямок'),
        ),
        migrations.AlterField(
            model_name='mediatorprofessionaldirections',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Чим більша вага, тим далі елемент буде у списку значень поля', verbose_name='Вага'),
        ),
    ]
