# Generated by Django 4.2.4 on 2024-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_mediatoreducation_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatoreducation',
            name='qualification_en',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Кваліфікація'),
        ),
        migrations.AddField(
            model_name='mediatoreducation',
            name='qualification_uk',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Кваліфікація'),
        ),
    ]
