# Generated by Django 4.2.4 on 2023-08-23 12:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('weight', models.PositiveSmallIntegerField(default=0, help_text='Чим більша вага, тим нижче ресурс буде у меню', verbose_name='Вага')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурси',
                'db_table': 'recources',
                'ordering': ('weight', 'created_at', 'title'),
            },
        ),
    ]
