# Generated by Django 4.2.4 on 2023-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Відображати на сайті'),
        ),
    ]
