# Generated by Django 4.2.4 on 2023-08-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(default=' ', max_length=127, verbose_name='Мітка для URL'),
            preserve_default=False,
        ),
    ]
