# Generated by Django 4.2.4 on 2023-08-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(max_length=127, unique=True, verbose_name='Мітка для URL'),
        ),
    ]
