# Generated by Django 4.2.4 on 2024-04-05 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='resource',
            name='content_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
