# Generated by Django 4.2.4 on 2023-08-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0007_alter_mediator_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('case_number', models.CharField(max_length=255, verbose_name='Номер справи')),
                ('case_date', models.DateField(verbose_name='Дата справи')),
                ('mediator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.mediator')),
            ],
            options={
                'verbose_name': 'Справа',
                'verbose_name_plural': 'Справи',
                'db_table': 'cases_list',
            },
        ),
    ]
